// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.
#pragma once

#include <frc2/command/SubsystemBase.h>
#include "ctre/Phoenix.h"
#include <frc/motorcontrol/Talon.h>
#include <rev/CANSparkMax.h>

/**
 * Intake Subsystem header file declaring associated functions and 
 * member variables
 *
 * @author 2826WaveRobotics
 */
class Intake: public frc2::SubsystemBase 
{
    public:
        Intake();

        void Periodic() override;
        void SimulationPeriodic() override;
        
        double GetIntakeArmSpeed();
        double GetIntakeRollerSpeed();

        void SetIntakeArmSpeed(double speed);
        void SetIntakeRollerSpeed(double speed);


    private:

        ctre::phoenix::motorcontrol::can::TalonSRX *m_intakeArm;
        ctre::phoenix::motorcontrol::can::TalonSRX *m_intakeRoller;
};