// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer.

#pragma once

#include <frc/smartdashboard/SendableChooser.h>
#include <frc2/command/Command.h>
#include <frc/XboxController.h>

#include "subsystems/Drive.h"
#include "subsystems/Intake.h"
#include "commands/AutonomousCommand.h"

class RobotContainer {

public:

    frc2::Command* GetAutonomousCommand();
    static RobotContainer* GetInstance();

    // The robot's subsystems
    Drive m_drive;
    Intake m_intake;

    // controllers
    frc::XboxController *getDriverJS();
    frc::XboxController *getOperatorJS();

private:

    RobotContainer();

    // Assign controller port
    frc::XboxController m_driverJS{0};
    frc::XboxController m_operatorJS{1};

    // Auto Chooser
    frc::SendableChooser<frc2::Command*> m_chooser;

    AutonomousCommand m_autonomousCommand;
    static RobotContainer* m_robotContainer;

    void ConfigureButtonBindings();
};


// This function is to call to get instance from the .cpp file and return the singleton pointer
RobotContainer* GetContainer();