// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

#include "subsystems/Intake.h"
#include <frc/smartdashboard/SmartDashboard.h>

/**
 * Intake Subsystem implementation
 * 
 * @author 2826WaveRobotics
*/
Intake::Intake()
{
    SetName("Intake");
    SetSubsystem("Intake");
    
    m_intakeArm = new ctre::phoenix::motorcontrol::can::TalonSRX(15);
    m_intakeRoller = new ctre::phoenix::motorcontrol::can::TalonSRX(17);
}

void Intake::Periodic() 
{
    // Put code here to be run every loop
}

void Intake::SimulationPeriodic() 
{
    // This method will be called once per scheduler run when in simulation
}

void Intake::SetIntakeArmSpeed(double speed)
{
    double intakeSpeed = std::clamp(speed, -1.0, 1.0);
    m_intakeArm->Set(ctre::phoenix::motorcontrol::ControlMode::PercentOutput, intakeSpeed);
}

void Intake::SetIntakeRollerSpeed(double speed)
{
    double intakeSpeed = std::clamp(speed, -1.0, 1.0);
    m_intakeRoller->Set(ctre::phoenix::motorcontrol::ControlMode::PercentOutput, intakeSpeed);
}